import { Buffer } from "node:buffer";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { formatCurrency, formatDate } from "@/lib/utils/format";

type PaymentRecord = {
  id: string;
  gym_id: string;
  membership_id: string;
  amount_paise: number;
  method: string;
  received_on: string;
  reference_code: string | null;
};

type ReceiptRecord = {
  receipt_number: string;
};

type MembershipRecord = {
  members: {
    full_name: string;
    phone: string;
  };
};

type GymRecord = {
  name: string;
  phone: string | null;
  address: string | null;
  gst_number: string | null;
};

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ paymentId: string }> },
) {
  const { paymentId } = await params;
  const supabase = createSupabaseServerClient();

  const { data: payment } = await supabase.from("payments").select("*").eq("id", paymentId).single();
  if (!payment) {
    return new NextResponse("Not found", { status: 404 });
  }

  const [{ data: receipt }, { data: membership }, { data: gym }] = await Promise.all([
    supabase.from("receipts").select("receipt_number").eq("payment_id", paymentId).maybeSingle(),
    supabase
      .from("memberships")
      .select("id, members!inner(full_name, phone)")
      .eq("id", (payment as PaymentRecord).membership_id)
      .single(),
    supabase.from("gyms").select("name, phone, address, gst_number").eq("id", (payment as PaymentRecord).gym_id).single(),
  ]);

  const typedPayment = payment as PaymentRecord;
  const typedReceipt = receipt as ReceiptRecord | null;
  const typedMembership = membership as MembershipRecord | null;
  const typedGym = gym as GymRecord | null;

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 32,
    y: 32,
    width: 531,
    height: 778,
    color: rgb(0.07, 0.07, 0.07),
  });

  page.drawText(typedGym?.name ?? "RepCore Gym", {
    x: 56,
    y: 770,
    size: 24,
    font: bold,
    color: rgb(0.96, 0.97, 0.98),
  });
  page.drawText("Payment Receipt", { x: 56, y: 736, size: 14, font, color: rgb(0.54, 0.58, 0.65) });

  const rows: Array<[string, string]> = [
    ["Receipt", typedReceipt?.receipt_number ?? "Pending"],
    ["Member", typedMembership?.members.full_name ?? "Unknown"],
    ["Phone", typedMembership?.members.phone ?? "Unknown"],
    ["Amount", formatCurrency(typedPayment.amount_paise)],
    ["Method", typedPayment.method],
    ["Received on", formatDate(typedPayment.received_on)],
    ["Reference", typedPayment.reference_code ?? "-"],
    ["Gym phone", typedGym?.phone ?? "-"],
    ["GST", typedGym?.gst_number ?? "-"],
  ];

  let y = 680;
  rows.forEach(([label, value]) => {
    page.drawText(label, { x: 56, y, size: 12, font: bold, color: rgb(0.54, 0.58, 0.65) });
    page.drawText(value, { x: 220, y, size: 13, font, color: rgb(0.96, 0.97, 0.98) });
    y -= 40;
  });

  page.drawText("Generated by RepCore", {
    x: 56,
    y: 80,
    size: 11,
    font,
    color: rgb(0.54, 0.58, 0.65),
  });

  const bytes = await pdf.save();
  const body = Buffer.from(bytes);

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="receipt-${paymentId}.pdf"`,
    },
  });
}
